"""Public worker execution contract generated by the orchestrator.

This is deliberately a narrow projection of a task. It contains the public
verification command and delivery expectations, never external evaluator
configuration or material.
"""


def build_execution_contract(task: dict, worktree: str, *, recovery_feedback: str | None = None) -> str:
    verify_cmd = task.get("verify_cmd") or "true"
    lines = [
        "Execution contract:",
        f"- Working directory: {worktree}",
        f"- Visible verification command: {verify_cmd}",
        f"- Delivery mode: {task['delivery_mode']}",
        "- Run the visible verification command in the working directory before claiming completion.",
        "- Commit the candidate changes in the working directory before claiming completion.",
        "- Submit the committed candidate according to the task's delivery mode.",
        "",
        "Task brief:",
        task["brief"].rstrip(),
    ]
    if recovery_feedback:
        lines.extend(["", "Recovery guidance from the previous attempt:", recovery_feedback.rstrip()])
    return "\n".join(lines) + "\n"
